### ISSUE TITLE
Why is the SWG sparse matrix indexed by [dst, src]?

### ISSUE THREAD

**Issue by sbromberger** [sbromberger/SimpleWeightedGraphs.jl#10]
This requires an unnecessary transpose on creation and unintuitive indexing.

**Comment by sbromberger** [comment]
@jpfairbanks is there any performance or other penalty for indexing a sparse matrix by row instead of by column?

**Comment by jpfairbanks** [comment]
Yes the columns are contiguous instead of the rows. You can swap the src dst arrays at creation to avoid the transpose

**Comment by sbromberger** [comment]
Um, wait. Right now we've got a sparse matrix that represents an adjacency matrix indexed by [dst, src]. Is there any advantage to doing that over having one indexed by [src, dst]?

**Comment by sbromberger** [comment]
Answering my own question: indexing by `dst, src` makes `outneighbors` fast. Since `outneighbors` is generally what we want, this makes sense.
