### ISSUE TITLE
Recommendation on plotting weighted graphs

### ISSUE THREAD

**Issue by BoundaryValueProblems** [sbromberger/SimpleWeightedGraphs.jl#12]
I want to plot a weighted graph with the edge width proportional to the corresponding edge weight. Is there any good plotting function/package for this? Since I'm familiar with Plots.jl, I want to use it if possible, but Plots.jl functions do not accept LightGraphs/SimpleWeightedGraphs data structure.
Thanks for your help!
BVPs

**Comment by sbromberger** [comment]
It is possible to plot `SimpleWeightedGraphs` using Plots, but you need PlotRecipes for it (as you need for any `AbstractGraph`):
```
julia> using LightGraphs, SimpleWeightedGraphs, Plots, PlotRecipes

julia> g = smallgraph(:house)
{5, 6} undirected simple Int64 graph

julia> sg = WGraph(g)
{5, 6} undirected simple Int64 graph with Float64 weights

julia> graphplot(sg)
```
yields

![screen shot 2017-12-04 at 06 47 35](https://user-images.githubusercontent.com/941359/33558565-08ec67c2-d8bf-11e7-87d7-a473912f01de.png)


As to having the edge weights influence the plot widths, that would probably require a PR to PlotRecipes.

**Comment by mkborregaard** [comment]
Yes: https://github.com/JuliaPlots/PlotRecipes.jl/issues/39
Plotting graphs is really an area with lots of nice possibilities for improvement :-)

**Comment by BoundaryValueProblems** [comment]
@sbromberger Thank you very much for showing those lines! Actually, I ended up writing my own functions (in Plots) to do so for a specific graph. I also learned how to put the arrowhead in the middle of a directed edge instead of either head or tail. @mkborregaard, I'll think about whether I can make some of my functions general enough to contribute to the github repository.

**Comment by sbromberger** [comment]
@BoundaryValueProblems -

> I'll think about whether I can make some of my functions general enough to contribute to the github repository.

Please do this if you can.
