### ISSUE TITLE
Performance issue while adding edges

### ISSUE THREAD

**Issue by annimesh2809** [sbromberger/SimpleWeightedGraphs.jl#2]
I tried running the example in `README.md` but Julia v0.6 gave a warning:
```julia
julia> add_edge!(g, 1, 2, 0.5)
WARNING: Note: adding edges to this graph type is not performant.
true
```

`ProfileView` showed type instability for the `add_edge!` method.
```julia
using LightGraphs, SimpleWeightedGraphs, ProfileView

function f()
    g = SimpleWeightedGraph()
    for i in 1:1000
        add_vertex!(g)
        add_edge!(g,1,i,0.2)
    end
    g
end

f();
Profile.clear()
@profile f()
ProfileView.view()
```

Am I doing something wrong here?
I need a performant weighted undirected graph for my work.

**Comment by sbromberger** [comment]
The warning is deliberate. Adding edges to a `SimpleWeightedGraph` is not performant as we're inserting into a sparse matrix.

As for type instability, I'm not seeing it:

```
julia> g = SimpleWeightedGraph(10)
{10, 0} undirected simple Int64 graph with Float64 weights

julia> @code_warntype(add_edge!(g,1,3,0.5))
Variables:
  #self#::LightGraphs.#add_edge!
  g::SimpleWeightedGraphs.SimpleWeightedGraph{Int64,Float64}
  x::Int64
  y::Int64
  z::Float64

Body:
  begin
      return $(Expr(:invoke, MethodInstance for add_edge!(::SimpleWeightedGraphs.SimpleWeightedGraph{Int64,Float64}, ::SimpleWeightedGraphs.SimpleWeightedEdge{Int64,Float64}), :(SimpleWeightedGraphs.add_edge!), :(g), :($(Expr(:new, SimpleWeightedGraphs.SimpleWeightedEdge{Int64,Float64}, :(x), :(y), :(z))))))
  end::Bool
```

**Comment by sbromberger** [comment]
If you want to make things a bit faster, initialize the graph with the number of vertices you need:
```
g = SimpleWeightedGraph(1000)
```

**Comment by annimesh2809** [comment]
Yes, `@code_warntype` does not show any warnings. However, `ProfileView` marks certain bars red.

![unstable](https://user-images.githubusercontent.com/15063205/28243868-6b2143d6-69f7-11e7-891a-33b837fbbd68.png)

It states that line 9 of `overrides.jl` causes problems. I looked upon it and this is the line:
```julia
g.weights = vcat(g.weights, emptycols')
```

So, I ran the lines of the function `add_vertices!` in the REPL one by one, with `g = SimpleWeightedGraph(3)` and `n=3`. Then I used `@code_warntype` on line 9 and it shows some type instability. Here is the working code:

```julia
using LightGraphs, SimpleWeightedGraphs

g = SimpleWeightedGraph(3);
n = 3;
T = eltype(g);
U = weighttype(g);
(nv(g) + one(T) <= nv(g)) && return false;       # test for overflow
emptycols = spzeros(U, nv(g) + n, n);
g.weights = hcat(g.weights, emptycols[1:nv(g), :]);
g.weights = vcat(g.weights, emptycols');

@code_warntype hcat(g.weights, emptycols[1:nv(g), :])  # shows some type instability
@code_warntype vcat(g.weights, emptycols')            # also shows type instablity

```
I output was large so I did not paste it here.

**Comment by sbromberger** [comment]
I'm not sure that intermediate type instability is an issue. Are you having a specific problem with the package? You should never be adding vertices one at a time to either SimpleWeightedGraph or SimpleGraph.

**Comment by sbromberger** [comment]
Also, to make graph creation faster, instead of adding edges one by one, you can use one of the other constructors: using `I, J, V` vectors might give you better bulk performance.

In short, though, this graph structure is not optimized for large numbers of mutations. If that's what you need then you might be better off with something else.

**Comment by annimesh2809** [comment]
Thanks @sbromberger. I will try those tweaks you mentioned.

**Comment by sbromberger** [comment]
Cool. Feel free to open up issues if you find unexpected regressions or performance problems. This is a relatively new package and some bugs are inevitable.
