### ISSUE TITLE
Zero-weight edges are ignored

### ISSUE THREAD

**Issue by dourouc05** [sbromberger/SimpleWeightedGraphs.jl#24]
I was debugging things in my code when I noticed that the number of edges that SimpleWeightedGraphs remembered is very low (289 instead of 3198). I found that edges whose weight is zero are simply ignored. Taking the README example: 

```julia
g = SimpleWeightedGraph(3)
add_edge!(g, 1, 2, 0.5)
add_edge!(g, 2, 3, 0.8)
add_edge!(g, 1, 3, 0.0) # Weight changed to zero
```

The resulting graph has only two edges: 

```
julia> g
{3, 2} undirected simple Int64 graph with Float64 weights

julia> collect(edges(g))
2-element Array{SimpleWeightedGraphs.SimpleWeightedEdge{Int64,Float64},1}:
 Edge 1 => 2 with weight 0.5
 Edge 2 => 3 with weight 0.8
```

Is this behaviour expected? To say the least, I would say not… Is it documented anywhere? Would it be possible to add a warning in `add_edge!` when the weight is zero (before it gets fixed)?

**Comment by sbromberger** [comment]
This is expected behavior. See, e.g., https://stackoverflow.com/a/48994712/7081717. There is no good workaround.

**Comment by sbromberger** [comment]
That said, a PR that warns on zero weights would be welcome.

**Comment by dourouc05** [comment]
I'm working on it, then!

**Comment by sbromberger** [comment]
If you wanted to put something in the README as well, that'd be awesome :)
