### ISSUE TITLE
massive retooling of package underway

### ISSUE THREAD

**Issue by sbromberger** [sbromberger/SimpleWeightedGraphs.jl#31]
Given the new `Adjoint` functionality in 1.0, it's probably time to rethink how we backstore the data in SimpleWeightedGraphs. This will likely mean a substantial overhaul.

cc @simonschoelly

**Comment by simonschoelly** [comment]
What was actually the reason for transposing the adjacency matrix?

And is there a reason why this package works with a sparse adjacency matrix and not with a adjacency list like `SimpleGraph`?

**Comment by sbromberger** [comment]
> What was actually the reason for transposing the adjacency matrix?

Because SparseMatrixCSC is column-major, and adjacency matrices are typically row-major. Since most of the traversal operations focus on outgoing edges, it is important that the outneighbors are close together (adjacent) in memory. 

> And is there a reason why this package works with a sparse adjacency matrix and not with a adjacency list like SimpleGraph?

Yes. This has better cache performance for very large graphs.
