### ISSUE TITLE
Support for complex weights

### ISSUE THREAD

**Issue by activexray** [sbromberger/SimpleWeightedGraphs.jl#49]
I think support for complex weights would be very beneficial for anyone solving controls problems. I can't seem to tell if there was any justification for only supporting reals.

**Comment by sbromberger** [comment]
Complex numbers are not orderable, so using them as weights wouldn't be appropriate here (how would you use them to calculate shortest paths, for example?) If you need to associate complex numbers with edges, MetaGraphs.jl might be appropriate.

**Comment by activexray** [comment]
Oh interesting. I'm trying to write some signal flow analysis code, so I'm trying to search for the best solution. I'll check out MetaGraphs. Thank you.
