### ISSUE TITLE
Weighted `degree`

### ISSUE THREAD

**Issue by Tokazama** [sbromberger/SimpleWeightedGraphs.jl#51]
Would a weighted implementation of `degree` be a welcome contribution here? I assume overloading `degree` would be the best approach.

**Comment by Tokazama** [comment]
After more reading perhaps a better term would be `strength`. This seems to be used in other graph ecosystems and would allow continued use of `degree` without any potential breaking changes or misunderstandings.

**Comment by simonschoelly** [comment]
After thinking a bit about this problem, I think something such as `weighted_degree` or `degree_weighted` seems appropriate to me. I would not overload the default `degree` method for now, as there might  different interpretations what weighted degrees mean.

It would actually be possible, to also implement this in LightGraphs. Then the signatures would be something like
```
weighted_degree(g, weights=weights(g))
weighted_degree(g, u, weights=weights(g))
```
The advantage of this is, that it would also work with SimpleGraphs (where weights(g) is just a matrix full of ones) and with MetaGraphs.jl. Also it would be possible to submit a custom weight matrix.

@sbromberger  What do you think?

**Comment by Tokazama** [comment]
Just for reference on where I got `strength`

* https://igraph.org/r/doc/strength.html
* https://rdrr.io/cran/simplegraph/man/strength.html
* https://sites.google.com/site/bctnet/measures/list

`weighted_degree` has a much clearer meaning though.

**Comment by sbromberger** [comment]
What is weighted degree?

**Comment by sbromberger** [comment]
Ah. It’s the sum of the weights of a node’s neighbors. Do we need something that is essentially a one-liner that also requires an external data structure?

**Comment by Tokazama** [comment]
What data structure are you referring to?

If it's implemented in SimpleWeightedGraphs then it is a one liner but I assume it would be more complicated to implement in LightGraphs. Wouldn't it require iterating over all possible edges and identifying those edges with the appropriate source and destination?

The measurement is useful to have readily available because it is used in a lot of downstream measures. [Complex network measures of brain connectivity: uses and interpretations](https://www.ncbi.nlm.nih.gov/pubmed/19819337) summarizes some of the weight based measures I'm referring to (Sorry, I couldn't find a free version). If you can't get past the paywall, it's just a lot of what's in LightGraphs that uses weights instead 1 and 0 at edges.

**Comment by sbromberger** [comment]
Isn't it simply
```
weighted_degree(g, v, w=weights(g)) = sum(w[v, neighbors(g, v)]))
```
?

**Comment by Tokazama** [comment]
I assumed you would want to avoid reallocating all of the weights that are already stored in the graph.

**Comment by simonschoelly** [comment]
`weighted_degree(g, v, w=weights(g)) = sum(@view w[v, neighbors(g, v)])` might be slightly faster.

Another way would be to create a version of the weighted Rich Club Coefficient for LightGraphs and add this function as a non exported internal function. Then if we realize that it is used in other places, we can still export it later.

**Comment by sbromberger** [comment]
> I assumed you would want to avoid reallocating all of the weights that are already stored in the graph.

Of course. "First correct, then fast."

**Comment by sbromberger** [comment]
> Another way would be to create a version of the weighted Rich Club Coefficient for LightGraphs and add this function as a non exported internal function. Then if we realize that it is used in other places, we can still export it later.

Seems like a cop-out. If it's important enough to include as new functionality, it should be important enough to export. What's the key issue here? I feel like I'm missing some larger context.

**Comment by simonschoelly** [comment]
This is a functionality used for a weighted version of this rich club coefficient that was recently talked about on Slack. 

A weighted version of a degree is basically what you get when interpreting the weight of an edge as the number of edges in a multigraph that have the same endpoints.

That paper also has some other interesting versions of some graph statistics.

> I assumed you would want to avoid reallocating all of the weights that are already stored in the graph.
It is not always necessary, that `weights(g)` allocates a new matrix, it could as well be, that it just a view into a matrix. for example for SimpleGraph, the datastructure returned by `weights(g)` does only store the number of vertices in that graph.

**Comment by Tokazama** [comment]
I'd be happy to make an attempt at a pull request into LightGraphs for this if you agree it's pertinent. 

@simonschoelly, I've been implementing those other measures as my introduction into graph theory and I hope to translate some work from the human connectome project into Julia. I'm still getting comfortable with the JuliaGraphs ecosystem and once I'm more oriented I could make some more ambitious contributions.

**Comment by sbromberger** [comment]
I think my current preference would be to implement rich club in LightGraphs with "weightedness" being a (dispatch) option. I don't think we need exported `weighted_degree` functions at this point, but if you wanted to break them out as utility functions for internal use by rich club, then that'd be ok (and I realize this is a complete reversal of my stance in https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl/issues/51#issuecomment-523080605). Hopefully they'd be inlined.

**Comment by rodrigolece** [comment]
I new to the JuliaGraphs ecosystem but if I understand correctly you want to keep weights out of LighGraphs right? If that's the case I don't see why you would need to implement `weigthed_degree` for `SimpleGraph` since by definition it would be the same as `degree`. 

+1 for this feature! In my research I deal with weighted graphs and even though it could be a one-liner, it's basic functionally that I would expect (and which is already implemented in igraph and Networkx).

**Comment by sbromberger** [comment]
Hey all, I'm going to close this out for housekeeping purposes. I don't think there's been a compelling argument for making a one-line utility function for `weighted_degree` and if we assume that `neighbors` is sufficiently performant, the one-liner will be pretty efficient.

Happy to reopen if people want to talk more about it though.
