### ISSUE TITLE
No weighted node functionality?

### ISSUE THREAD

**Issue by joseortiz3** [sbromberger/SimpleWeightedGraphs.jl#54]
Weighted nodes are in a sense dual to weighted edges. Is there no capability for handling weighted nodes?

**Comment by sbromberger** [comment]
Sorry for the delay - no, we don't have weighted nodes. If you need node metadata, you might want to check out MetaGraphs.

**Comment by joseortiz3** [comment]
Hmm. `SimpleWeightedGraphs` -> `SimpleEdgeWeightGraphs` ;)
I'll make a doc change PR.
